kind: pipeline
type: docker
name: default

steps:
- name: test
  image: python:3.9-slim
  commands:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pytest
- name: mypy
  image: python:3.9-slim
  commands:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - mypy .
