# Все настройки можно перекрыть, согласно конфигурации и возможностям dynaconf, через переменные окружения.
# Однако, настройки для конкретных IM следует задавать через env с особым вниманием:
# название IM и все переменные идут в нижнем регистре - HLB_IM.gitter.token=12345
# Так не возникнет проблем при объединении настроек.
# Через переменные окружения настройка приложения идет так:
# HLB_DEBUG=1; Для настроек раздела default через префикс envvar_prefix и одно нижнее подчеркивание (HLB_).
# HLB_im__cli__signature_start_command=#; Для настроек вложенных разделов через двойное нижнее подчеркивание.

# Общие настройки.
[default]
# Имя бота.
title = "HLB"
# Отладочный режим работы.
debug = true
# Название IM платформы для которой будет запущен бот. По умолчанию cli для проверки работы.
default_im = "cli"

# Настройки для каждого IM.
[default.im]

# CLI для тестирования команд.
[default.im.cli]
# Символ, начиная с которого будет распознваться команда для бота.
signature_start_command = "/"

# gitter.im
[default.im.gitter]
signature_start_command = "/"
signature_message_bot = "**[HLB]**"
token = ""
active_room = ""

# telegram.org
[default.im.telegram]
signature_start_command = "/"
token = 0
# Id пользователя, для которого доступны приватные команды.
super_user_id = 0

# Настройки для репозиториев запросов ко внешним источникам информации.
[default.repos]
[default.repos.reddit]
client_id = ""
client_secret = ""
# Список интересных сабреддитов.
subs = []
